### ISSUE TITLE
What happens if an episode is no longer present in a feed?

### ISSUE THREAD

**Issue by funkenstrahlen** [podigee/podigee-quickplay#4]
* enter a feed
* select an episode
* embed the player in my website
* wait for some weeks
* episode is removed from the podcast feed, because some podcasts only keep recent episodes in their feed (feedburner!)
* is the player still valid? does podigee-quickplay keep the json cached?

**Comment by benzimmer** [comment]
Short answer:
Yes, it still valid because the configuration for the player is persisted in a database.

Long answer:
The configuration for an episode is written into a redis store when it is first created. Currently this is implemented as a cache without any expiry. The cache key is calculated from the feed address and the episode guid. So it's probably better to call it database than cache :)

Of course you could also just use redis as a normal cache by expiring entries or cleaning up old entries now and then semi-automatically. With quickplay.podigee.com we plan to use it as a persistent data store, so playback will work even when episodes leave the feed (intentionally or unintentionally).

Apart from that I would like to add the capability to parse paged feeds to the app, so the whole back-catalog can be used for quickplaying.
